<a href="https://colab.research.google.com/github/RohanBurad/CONCEPTS-OF-PYTHON/blob/main/NUMPY%2Cipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY CHAPTER 4

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,11])
print(type(x))

<class 'numpy.ndarray'>


2D & 3D ARRAY

In [ ]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])  #USING for loop for printing array

for i in Y:
  for j in i:
      print(j)

1
2
3
4
5
6
7
8
9


ZEROS

In [ ]:
import numpy as np
Z = np.zeros(10)
print(Z)
E = np.zeros((5,3))
print(E)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ONES

In [ ]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


ARANGE

In [ ]:
b = np.arange(1,100,2) #PROVIDES RANGE for odd numbers
c = np.arange(0,100,2) #PROVIDES RANGE for even numbers
print(b)
print(c)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


INDEXING , SLICING & RESHAPING

In [ ]:
print(c[2])
print(b[20])

4
41


In [ ]:
print(c[2:56]) #slicing
print(b[1::6]) #jumping
for i in c:
  print(i)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[ 3 15 27 39 51 63 75 87 99]
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [ ]:
#RESHAPING
x = np.array([1,2,3,4,5,6,7,11])
re = x.reshape(4,2)
print(re)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 11]]


MATHEMATICAL & STATICAL METHODS

In [ ]:
minimum = np.min(c)  # minimum
print(minimum)
max = np.max(b)  # maximum
print(max)
y=[1,2,3,4,5]
z=[1,2,3,4,5,6]
med = np.median(y) # median
print(med)
mod = np.mean(z)  # mean
print(mod)
std = np.std(z)  # standard deviation
print(std)
Std = np.std(Y)  # standard deviation in 3D ARRAY
print(Std)
sum = np.sum(y) # sum of elements in 1D Array
Sum = np.sum(Y)  # sum of elements in 3D Array
print(sum)
print(Sum)

0
99
3.0
3.5
1.707825127659933
2.581988897471611
15
45


ITERATION OF 3D ARRAY

In [ ]:
for i in Y:
      print(i)
print("\n")
for i in Y:
  for j in i:
      print(j)

[1 2 3]
[4 5 6]
[7 8 9]


1
2
3
4
5
6
7
8
9
